version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Africa/Johannesburg"
    open-pull-requests-limit: 10
    labels:
      - "type:maintenance"
      - "area:devops"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:30"
      timezone: "Africa/Johannesburg"
    open-pull-requests-limit: 10
    labels:
      - "type:maintenance"
      - "area:devops"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Africa/Johannesburg"
    open-pull-requests-limit: 10
    labels:
      - "type:maintenance"
      - "area:devops"
