name: Markdown

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

permissions:
  contents: read

jobs:
  markdown:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Markdown lint
        uses: DavidAnson/markdownlint-cli2-action@v23
        with:
          globs: |
            **/*.md
            !**/bin/**
            !**/obj/**
            !node_modules/**
